# Generated by Django 3.1.7 on 2021-03-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210315_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pric',
            field=models.IntegerField(verbose_name='سعرالكشف :'),
        ),
    ]
