# Generated by Django 3.1.7 on 2021-03-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210317_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_details',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الشارع'),
        ),
        migrations.AddField(
            model_name='profile',
            name='dep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spicialist_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص فى'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whating_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='وقت العمل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whating_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='وقت الانتظار'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الاسم :'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='من انا :'),
        ),
    ]
