# Generated by Django 3.1.7 on 2021-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210317_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spicial',
            field=models.CharField(choices=[('باطنه', 'باطنه'), ('اوعيه', 'اوعيه'), ('عظام', 'عظام'), ('قلب', 'قلب'), ('جلديه', 'جلديه'), ('اسنان', 'اسنان'), ('كبد', 'كبد')], default=1, max_length=50, verbose_name='التخصص'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default=1, max_length=50, verbose_name='النوع'),
            preserve_default=False,
        ),
    ]
