# Generated by Django 3.1.7 on 2021-03-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210323_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='فيس بوك'),
        ),
        migrations.AddField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='جوجل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تويتر'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spicial',
            field=models.CharField(choices=[('جلديه', 'جلديه'), ('باطنه', 'باطنه'), ('عظام', 'عظام'), ('كبد', 'كبد'), ('اوعيه', 'اوعيه'), ('اسنان', 'اسنان'), ('قلب', 'قلب')], max_length=50, verbose_name='التخصص'),
        ),
    ]
