# Generated by Django 3.1.7 on 2021-03-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210323_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='وقت لانضمام'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='spicial',
            field=models.CharField(choices=[('كبد', 'كبد'), ('جلديه', 'جلديه'), ('قلب', 'قلب'), ('اسنان', 'اسنان'), ('باطنه', 'باطنه'), ('عظام', 'عظام'), ('اوعيه', 'اوعيه')], max_length=50, verbose_name='التخصص'),
        ),
    ]
