# Generated by Django 3.1.7 on 2021-03-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210323_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_at',
            field=models.DateTimeField(verbose_name='وقت الانضمام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spicial',
            field=models.CharField(choices=[('باطنه', 'باطنه'), ('قلب', 'قلب'), ('جلديه', 'جلديه'), ('اوعيه', 'اوعيه'), ('كبد', 'كبد'), ('عظام', 'عظام'), ('اسنان', 'اسنان')], max_length=50, verbose_name='التخصص'),
        ),
    ]
